### ISSUE TITLE
Generated content element brings fatal errors

### ISSUE THREAD

**Issue by cweiske** [FluidTYPO3/builder#95] opened 2015-10-21 12:39 UTC
The generated content element has the following code inside:

    <f:layout name="{v:extension.loaded(extensionName: 'fluidcontent_core', then: 'ContentCore', else: 'Content')}" />

This creates fatal errors in typo3:

    Fatal error: Call to a member function getViewHelper() on null
    in .../typo3temp/Cache/Code/fluid_template/MyFluidTest_Content_action_render_c0944f648354597d7e546dc495725d69b7a21978.php on line 17

**Comment by NamelessCoder** [comment] 2015-10-22 12:22
Damn, Christian, I think you just uncovered a bug in Fluid itself. That doesn't happen often! And by the way, it's one that I removed the causes for, in the standalone Fluid that's going to be merged into TYPO3 soon. So although this problem would go away, here's the reason and how to avoid it for now:

* Fluid does not detect that an uncompilable ViewHelper is used in the `f:layout` node and so allows compiling, but when rendering the compiled template Fluid tries to call the uncompilable ViewHelper but with an incompatible context (statically rendered, no nodes present, etc).
* The symptom was prevented until now because almost all ViewHelpers were not compilable and would cause the compiler to be disabled - this has changed and now all Fluid ViewHelpers are compilable which means you're more likely to encounter this case from now on.
* It can be only avoided immediately by not using the ViewHelper in the `f:layout` node.
* It can be "avoided" in the longer run by making every last VHS ViewHelper compilable (not really a solution).

I would normally refer to the TYPO3 bug tracker but in this case that would be counter productive. It's a problem that will go away, it only affects an edge case - and we can of course avoid it. For now, please use the workaround suggested; just hardcode the Layout based on whether or not you use FluidcontentCore.

That being said, we should change the source code that EXT:builder generates until it can be safely used in compilable AND uncompilable templates alike.

**Closed** 2015-11-07 13:47 UTC
